# Generated by Django 5.2 on 2025-05-12 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0002_remove_purchase_sessions_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('session_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('logged_on', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='logged_sessions', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='sessions', to='checkout.purchase')),
            ],
        ),
    ]
