# Generated by Django 5.2 on 2025-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_sessions', models.PositiveIntegerField(default=1)),
                ('feature1', models.CharField(blank=True, max_length=255)),
                ('feature2', models.CharField(blank=True, max_length=255)),
                ('feature3', models.CharField(blank=True, max_length=255)),
                ('feature4', models.CharField(blank=True, max_length=255)),
                ('feature5', models.CharField(blank=True, max_length=255)),
                ('ideal_for', models.TextField(blank=True)),
            ],
        ),
    ]
