# Generated by Django 5.2 on 2025-05-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='name',
        ),
    ]
