# Generated by Django 5.2 on 2025-05-20 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_purchase_sessions_used'),
        ('user_profiles', '0008_userprofile_bio_userprofile_calendly_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='customer_email',
            field=models.EmailField(default='placeholder@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='subject_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profiles.subject'),
        ),
    ]
