# Generated by Django 5.2 on 2025-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='package_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
