# Generated by Django 5.2 on 2025-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_userprofile_package_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sessions_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
