# Generated by Django 5.2 on 2025-05-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0005_userprofile_first_name_userprofile_grade_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='package',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='package_assigned_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sessions_used',
        ),
    ]
