# Generated by Django 5.2 on 2025-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0006_remove_userprofile_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_sessions_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
